# Generated by Django 2.0.4 on 2018-04-17 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 11, 15, 13, 832751, tzinfo=utc)),
        ),
    ]
