# Generated by Django 2.0.4 on 2018-04-22 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_auto_20180420_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 8, 47, 1, 428775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 22, 8, 47, 1, 422764, tzinfo=utc)),
        ),
    ]
