# Generated by Django 2.0.4 on 2018-04-24 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_auto_20180423_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 12, 31, 8, 223568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 24, 12, 31, 8, 223568, tzinfo=utc)),
        ),
    ]
