# Generated by Django 2.0.4 on 2018-04-24 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_auto_20180424_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 12, 32, 0, 164416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 24, 12, 32, 0, 164416, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
